name: dfgreTeslimat
version: 1.1.0
main: me.dfgre.teslimat.Main
api-version: '1.21'
author: dfgre
commands:
  teslimat:
    description: "Teslimat menusunu acar."
    usage: "/<command> [yardim|reload]"
permissions:
  teslimat.admin:
    description: "Plugin reload yetkisi."
    default: op